### ISSUE TITLE
Temporary files included

### ISSUE THREAD

**Issue by NathanJPhillips** [porrey/rgbled#5]
The latest commit (3c537798f00b26b573f6a2951a602eb7cb82f605) added lots of temporary files to the project. We may need to update the .gitignore. There is a potentially useful version here: https://github.com/github/gitignore/blob/master/VisualStudio.gitignore.

**Comment by porrey** [comment]
Thanks. I had removed these prior to the check-in but it appears VS recreated them just prior. I'll add the proper ignores. Appreciate your help on this.

**Comment by porrey** [comment]
.gitignore added. Extra files removed.
